In [2]:
import numpy as np

In [7]:
test1 = np.array([0.26894142,  0.73105858])
assert np.amax(np.fabs(test1 - np.array([0.2689,  0.731]))) <= 1e-6

AssertionError: 

In [8]:
test1 = softmax(np.array([1,2]))

NameError: name 'softmax' is not defined

In [10]:
np.exp(1)/(np.exp(1)+np.exp(2))

0.2689414213699951

In [43]:
np.exp(20)/(np.exp(4)+np.exp(20))

0.99999988746483803

In [13]:
test1

array([ 0.26894142,  0.73105858])

In [30]:
test = lambda x:np.exp(x)/np.sum(np.exp(x), axis=0)

In [31]:
test(1)

1.0

In [32]:
test(test1)

array([ 0.26894142,  0.73105858])

In [33]:
test1

array([1, 2])

In [34]:
test1 = np.array([1,  2])

In [35]:
test([1, 2])

array([ 0.26894142,  0.73105858])

In [54]:
test = lambda x:np.exp(x)/np.sum(np.exp(x), axis=len(x.shape) - 1)

In [55]:
xm = np.matrix([[1, 2, 4], [10, 4, 11]])
print test(xm)
np.sum(test(xm), axis=1)

[[  4.20100661e-02   1.14195199e-01   8.43794734e-01]
 [  2.68762254e-01   6.66195022e-04   7.30571551e-01]]


matrix([[ 1.],
        [ 1.]])

In [56]:
np.sum(np.exp([[1, 2], [4, 20]]), axis=0)

array([  5.73164319e+01,   4.85165203e+08])

In [57]:
xm = np.array([1, 2, 4])
print test(xm)
np.sum(test(xm))

[ 0.04201007  0.1141952   0.84379473]


1.0

In [61]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=len(x.shape) - 1)

In [63]:
test1 = softmax(np.array([1,2]))
test1

array([ 0.26894142,  0.73105858])

In [64]:
assert np.amax(np.fabs(test1 - np.array([0.26894142,  0.73105858]))) <= 1e-6

In [66]:
test2 = softmax(np.array([[1001,1002],[3,4]]))
print test2
assert np.amax(np.fabs(test2 - np.array( [[0.26894142, 0.73105858], [0.26894142, 0.73105858]]))) <= 1e-6
#
#test3 = softmax(np.array([[-1001,-1002]]))
#print test3
#assert np.amax(np.fabs(test3 - np.array([0.73105858, 0.26894142]))) <= 1e-6

[[        nan         inf]
 [ 0.          0.73105858]]


/Users/alexruppelt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/Users/alexruppelt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in divide
  from ipykernel import kernelapp as app


AssertionError: 

In [79]:
a = np.array([[1001,1002],[3,4]])

In [80]:
tmp = np.max(a, axis = 1)
tmp

array([1002,    4])

In [81]:
a -= tmp.reshape((a.shape[0], 1))
a

array([[-1,  0],
       [-1,  0]])

In [82]:
a = np.exp(a)
a

array([[ 0.36787944,  1.        ],
       [ 0.36787944,  1.        ]])

In [83]:
tmp = np.sum(a, axis = 1)
tmp

array([ 1.36787944,  1.36787944])

In [84]:
a /= tmp.reshape((a.shape[0], 1))
a

array([[ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858]])

In [86]:
a.shape[1]

2

In [96]:
def softmax(x):
    tmp = np.max(x, axis=len(x.shape) - 1)
    x -= tmp.reshape((x.shape[0], 1))
    return np.exp(x)/np.sum(np.exp(x), axis=len(x.shape) - 1)

In [91]:
b = np.array([[1001,1002,1003],[3,4,6]])
b

array([[1001, 1002, 1003],
       [   3,    4,    6]])

In [94]:
tmp = np.max(b, axis=len(b.shape) - 1)
tmp

array([1003,    6])

In [95]:
b - tmp

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [98]:
test2 = softmax(np.array([[1001,1002],[3,4]]))
print test2
assert np.amax(np.fabs(test2 - np.array( [[0.26894142, 0.73105858], [0.26894142, 0.73105858]]))) <= 1e-6

test3 = softmax(np.array([[-1001,-1002]]))
print test3
assert np.amax(np.fabs(test3 - np.array([0.73105858, 0.26894142]))) <= 1e-6

[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]


In [99]:
x = np.array([[1, 2], [-1, -2]])

In [118]:
sigm = lambda x: 1/(np.exp(-x)+1)

In [108]:
from sklearn import dummy, datasets, metrics, cross_validation, linear_model

In [115]:
df = datasets.make_classification(1000, n_classes=2)
#clf = dummy.DummyClassifier()
clf = linear_model.LogisticRegression()
cross_validation.cross_val_score(clf, df[0], df[1], scoring='log_loss', cv=5)

array([-0.39573272, -0.28542756, -0.33689913, -0.34842678, -0.30675752])

In [119]:
sigm(x)

array([[ 0.73105858,  0.88079708],
       [ 0.26894142,  0.11920292]])

In [120]:
x.dot(1-x)

array([[ 4,  5],
       [-4, -5]])

In [121]:
1-x

array([[ 0, -1],
       [ 2,  3]])

In [122]:
x

array([[ 1,  2],
       [-1, -2]])

In [123]:
0.73105858*(1-0.73105858)

0.19661193260838358

In [124]:
np.multiply(x, 1-x)

array([[ 0, -2],
       [-2, -6]])

In [125]:
quad = lambda x: (np.sum(x ** 2), x * 2)
a = np.array(123.456)
#print "Running sanity checks..."
#gradcheck_naive(quad, )
#gradcheck_naive(quad, np.random.randn(3,))
#gradcheck_naive(quad, np.random.randn(4,5))

In [126]:
fx, grad = quad(a)

In [127]:
fx, grad

(15241.383936, 246.91200000000001)

In [133]:
b = np.random.randn(4,5)
it = np.nditer(b, flags=['multi_index'], op_flags=['readwrite'])
#while not it.finished:
    #print b[it.multi_index]

In [134]:
a = np.array([[3.0,4.0],[1, 2]])

In [139]:
tmp = np.sqrt(np.sum(a*a, axis = 1))

In [140]:
tmp.reshape((x.shape[0], 1))

array([[ 5.        ],
       [ 2.23606798]])

In [141]:
tmp

array([ 5.        ,  2.23606798])

In [142]:
a/tmp.reshape((a.shape[0], 1))

array([[ 0.6       ,  0.8       ],
       [ 0.4472136 ,  0.89442719]])

In [143]:
tmp.shape

(2,)

In [144]:
tmp.reshape((a.shape[0], 1)).shape

(2, 1)

In [145]:
import nltk

In [147]:
sentence = "I would like to go to New York and see Metlife building"

text = nltk.word_tokenize(sentence_ner)

In [176]:
x = [t[0] for t in nltk.pos_tag(text) if t[1] in ('NN', 'NNP')]

In [162]:
from nltk.tag import StanfordTagger

In [174]:
import os
os.environ["STANFORD_MODELS"] = "/Users/alexruppelt/nltk_data/taggers/stanford-ner"
import nltk.tag.stanford as st
tagger = st.NERTagger('/Users/alexruppelt/nltk_data/taggers/stanford-ner/classifiers/english.all.3class.distsim.crf.ser.gz', '/Users/alexruppelt/nltk_data/taggers/stanford-ner/stanford-ner.jar')
#tagger.tag('Rami Eid is studying at Stony Brook University in NY'.split()) 

In [175]:
java_path = "path/to/java" # replace this
os.environ['JAVAHOME'] = java_path

In [177]:
x

['New', 'York', 'Metlife', 'building']

In [187]:
nltk.ne_chunk(nltk.pos_tag(text))[6]

Tree('GPE', [('New', 'NNP'), ('York', 'NNP')])

In [188]:
from nltk import ne_chunk, pos_tag, word_tokenize
from nltk.tree import Tree

def get_continuous_chunks(text):
    chunked = ne_chunk(pos_tag(word_tokenize(text)))
    prev = None
    continuous_chunk = []
    current_chunk = []
    for i in chunked:
            if type(i) == Tree:
                    current_chunk.append(" ".join([token for token, pos in i.leaves()]))
            elif current_chunk:
                    named_entity = " ".join(current_chunk)
                    if named_entity not in continuous_chunk:
                            continuous_chunk.append(named_entity)
                            current_chunk = []
            else:
                    continue
    return continuous_chunk

my_sent = "WASHINGTON -- In the wake of a string of abuses by New York police officers in the 1990s, Loretta E. Lynch, the top federal prosecutor in Brooklyn, spoke forcefully about the pain of a broken trust that African-Americans felt and said the responsibility for repairing generations of miscommunication and mistrust fell to law enforcement."
get_continuous_chunks(my_sent)

['WASHINGTON', 'New York', 'Loretta E. Lynch', 'Brooklyn']

In [195]:
s = "I would like to go to New York and see Metlife building"
a = get_continuous_chunks(s)

In [201]:
for x in a:
    s = s.replace(x, "")

In [206]:
s = " ".join(s.split())

In [207]:
s

'I would like to go to and see building'

In [208]:
d = {}

In [209]:
d['a'].append('bbb')

KeyError: 'a'

In [212]:
s = "WASHINGTON -- In the wake of a string of abuses by New York police officers in the 1990s, Loretta E. Lynch, the top federal prosecutor in Brooklyn, spoke forcefully about the pain of a broken trust that African-Americans felt and said the responsibility for repairing generations of miscommunication and mistrust fell to law enforcement."
#nltk.pos_tag(word_tokenize(s))

In [214]:
nltk.pos_tag(word_tokenize('I will see things relatively easy'))

[('I', 'PRP'),
 ('will', 'MD'),
 ('see', 'VB'),
 ('things', 'NNS'),
 ('relatively', 'RB'),
 ('easy', 'JJ')]

In [224]:
a = [[2],[3,4,5]]

In [226]:
[x for x in a]

[[2], [3, 4, 5], [2], [3, 4, 5]]

In [1]:
from gensim.models import word2vec

In [4]:
sentences = word2vec.Text8Corpus('text8')

In [5]:
model = word2vec.Word2Vec(sentences, size = 100)

In [9]:
model.similarity('man', 'finance')

-0.056391865782355652

In [10]:
model.save('m1.txt')

In [14]:
model = word2vec.Word2Vec.load('m1.txt')

In [36]:
model.similarity('woman', 'vagina')

0.32435422545321674

In [45]:
model.most_similar(positive=['woman', 'king'], negative=['man'])

[(u'queen', 0.643710732460022),
 (u'princess', 0.5914874076843262),
 (u'prince', 0.5846543908119202),
 (u'son', 0.580888032913208),
 (u'elizabeth', 0.580187976360321),
 (u'throne', 0.5797484517097473),
 (u'empress', 0.5754742622375488),
 (u'regent', 0.5714478492736816),
 (u'matilda', 0.5669463276863098),
 (u'daughter', 0.5643543601036072)]

In [58]:
list1 = ['finance', 'sport', 'leisure', 'science', 'religion']
nouns = ['wake', 'police', 'prosecutor', 'spoke', 'pain', 'trust', 'law', 'enforcement']
res = {}
for item in list1:
    res[item] = 0
    for noun in nouns:
        #res[item].append(model.similarity(item, noun))
        res[item] +=model.similarity(item, noun)

In [60]:
model.similarity('finance', 'finance')

1.0

In [63]:
model['new_york']

KeyError: 'new_york'